version: "3.3"

volumes:
  yitaoio-static:
  gallery-static:
  gallery-media:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-enabled:/etc/nginx/sites-enabled:ro
      - yitaoio-static:/var/static/yitaoio:ro
      - gallery-static:/var/static/gallery:ro
      - gallery-media:/var/media:rw
    depends_on:
      - yitaoio
      - gallery
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:9-alpine
    env_file: env
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data:rw
    deploy:
      restart_policy:
        condition: any

  yitaoio:
    image: hb1412/yitao.io:latest
    depends_on:
      - db
    env_file: env
    volumes:
      - yitaoio-static:/code/static
      - ./settings.py:/code/config/settings/settings.py
    deploy:
      restart_policy:
        condition: any
        delay: 10s

  gallery:
    image: hb1412/gallery:latest
    volumes:
      - gallery-static:/code/static
      - gallery-media:/code/media
    deploy:
      restart_policy:
        condition: any
        delay: 10s
