version: "3.3"

volumes:
  yitaoio-static:
  yitaoio-media:
  gallery-static:
  ifthen-static:
  auth-static:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-enabled:/etc/nginx/sites-enabled:ro
      - yitaoio-static:/var/static/yitaoio:ro
      - yitaoio-media:/var/media/yitaoio:rw
      - gallery-static:/var/static/gallery:ro
      - ifthen-static:/var/static/ifthen:ro
      - auth-static:/var/static/auth:ro
    depends_on:
      - yitaoio
      - gallery
      - ifthen
      - auth
    ports:
      - 80:80
      - 443:443

  db:
    image: postgres:9-alpine
    env_file: env
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data:rw
    deploy:
      restart_policy:
        condition: any

  yitaoio:
    image: hb1412/yitao.io:latest
    depends_on:
      - db
      - redis
    env_file: env
    volumes:
      - yitaoio-static:/code/static
      - yitaoio-media:/code/media
      - ${PWD}/settings.py:/code/config/settings/settings.py
    deploy:
      restart_policy:
        condition: any
        delay: 10s

  redis:
    image: redis:5-alpine


  gallery:
    image: hb1412/gallery:latest
    volumes:
      - gallery-static:/code/static
    deploy:
      restart_policy:
        condition: any
        delay: 10s

  ifthen:
    image: hb1412/ifthen_client:latest
    volumes:
      - ifthen-static:/code/static
    deploy:
      restart_policy:
        condition: any
        delay: 10s

  auth:
    image: hb1412/auth:latest
    volumes:
      - auth-static:/code/static
    deploy:
      restart_policy:
        condition: any
        delay: 10s
